Core_Costumer/Core_Costumer/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Core_Costumer.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
        }
        public DbSet<Costumer> Customer { get; set; } // el segundo Customer es el nombre de la tabla de la base de datos
        //El Costumer entre diamantes, es el nombre de mi clase
    }
}

Core_Costumer/Core_Costumer/Models/Costumer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Core_Costumer.Models
{
    public class Costumer
    {
        [Key]
        public int Empid { get; set; }

        [Required(ErrorMessage = "Ingrese el nombre")]
        [Display(Name = "Nombre")]
        public string Empname { get; set; }

        [Required(ErrorMessage = "Ingrese el apellido")]
        [Display(Name = "Apellido")]
        public string Lastname { get; set; }

        [Required(ErrorMessage = "Ingrese el email")]
        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "Dirección de email inválido")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Ingrese la edad")]
        [Display(Name = "Edad")]
        [Range(20, 50)]
        public int Age { get; set; }

        [Required(ErrorMessage = "Ingrese la dirección")]
        [Display(Name = "Dirección")]
        public string Adress
        {
            get; set;
        }

    }
}

Core_Costumer/Core_Costumer/Models/ErrorViewModel.cs
using System;

namespace Core_Costumer.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Core_Costumer/Core_Costumer/Controllers/CostumerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Core_Costumer.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Core_Costumer.Controllers
{
    public class CostumerController : Controller
    {

        private readonly ApplicationDbContext _db;

        public CostumerController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var displaydata = _db.Customer.ToList();   //Custumer es el nombre de la tabla para entrar a los datos que almacena en ella. por medio del objeto _db que hace la conexión
            return View(displaydata);
        }
                                                        //Estos dos son los mismos métodos, pero sobrecargados, si elimino el primero, aún así funciona.
        [HttpGet]
        public async Task<IActionResult> Index(string empSearch)
        {
            ViewData["GetCostumersDetails"] = empSearch;//Dato compartido con la vista
            var empquery = from x in _db.Customer select x; //Query de EF, de la tabla Employee almacena en x
            if (!String.IsNullOrEmpty(empSearch))
            {
                empquery = empquery.Where(x => x.Empname.Contains(empSearch) || x.Email.Contains(empSearch)); //Agrega claususla Where
            }
            return View(await empquery.AsNoTracking().ToListAsync()); //Retorna el resultado del query como una lista asincrona que no pasa por _db
        }

        public IActionResult Create()
        {
            return View();  //Te regresa la vista  que se llama igual que el metodo
        }

        [HttpPost]
        public async Task<IActionResult> Create(Costumer nEmp)  //Este metodo nos lleva a llevar el formulario para agregar un empleado a la base de datos
        {
            if (ModelState.IsValid)
            {
                _db.Add(nEmp);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");  // si el empleado fue ingesado exitosamente, nos lleva a la pagina principal

            }

            return View(nEmp);  //En caso de haber una falla, se mantiene en la vista del formulario sin que re borren los datos ya ingresados.
        }

        public async Task<ActionResult> Detail(int? id) //Se pone ? porque puede que haya o no id.
        {
            if (id == null)
            {
                return RedirectToAction("Index");

            }

            var getEmpDetail = await _db.Customer.FindAsync(id);
            return View(getEmpDetail);
        }


        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var getEmpDetail = await _db.Customer.FindAsync(id);
            return View(getEmpDetail);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Costumer oldEmp)
        {
            if (ModelState.IsValid)
            {
                _db.Update(oldEmp);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(oldEmp);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var getEmpDetail = await _db.Customer.FindAsync(id);
            return View(getEmpDetail);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var getEmpDetail = await _db.Customer.FindAsync(id);
            _db.Customer.Remove(getEmpDetail);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }


    }
}

Core_Costumer/Core_Costumer/Views/Costumer/Create.cshtml
@model Core_Costumer.Models.Costumer

@{
    ViewData["Title"] = "Create";
}

<h1>Crear un nuevo cliente</h1>

<h4>Datos del cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Empname" class="control-label"></label>
                <input asp-for="Empname" class="form-control" />
                <span asp-validation-for="Empname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lastname" class="control-label"></label>
                <input asp-for="Lastname" class="form-control" />
                <span asp-validation-for="Lastname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar al inicio</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Core_Costumer/Core_Costumer/Views/Costumer/Delete.cshtml
@model Core_Costumer.Models.Costumer

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar cliente</h1>

<h3>¿Está seguro?</h3>
<div>
    <h4>Cliente:</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Empid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Empid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Empname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Empname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lastname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lastname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Regresar al inicio</a>
    </form>
</div>

Core_Costumer/Core_Costumer/Views/Costumer/Detail.cshtml
@model Core_Costumer.Models.Costumer

@{
    ViewData["Title"] = "Detail";
}

<h1>Detalles</h1>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Empid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Empid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Empname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Empname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lastname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lastname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Empid }) |
    <a asp-action="Index">Regresar al inicio</a>
</div>

Core_Costumer/Core_Costumer/Views/Costumer/Edit.cshtml
@model Core_Costumer.Models.Costumer

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar datos</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Empid" class="control-label"></label>
                <input asp-for="Empid" class="form-control" readonly />
                <span asp-validation-for="Empid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Empname" class="control-label"></label>
                <input asp-for="Empname" class="form-control" />
                <span asp-validation-for="Empname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lastname" class="control-label"></label>
                <input asp-for="Lastname" class="form-control" />
                <span asp-validation-for="Lastname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar al inicio</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Core_Costumer/Core_Costumer/Views/Costumer/Index.cshtml
@model IEnumerable<Core_Costumer.Models.Costumer>

@{
    ViewData["Title"] = "Index";
}

<h1>Inicio</h1>

<p>
    <a asp-action="Create">Nuevo cliente</a>
</p>

<form asp-action="Index" method="get">
    <p>
        <input type="search" placeholder="Ingresa nombre o email: " name="empSearch"
               value="@ViewData["GetCostumersDetails"]" style="width:500px;" />
        <input type="submit" value="Buscar" class="btn btn-primary" />
        <a asp-action="Index"> Ver todos</a>
    </p>

</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Empid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Empname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lastname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Adress)
            </th>
            <th>


            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Empid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Empname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lastname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Adress)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Empid }, new { @class = "btn btn-primary" }) |
                @Html.ActionLink("Detalles", "Detail", new { id = item.Empid }, new { @class = "btn btn-success" }) |
                @Html.ActionLink("Eliminar", "Delete", new { id = item.Empid }, new { @class = "btn btn-danger" })
            </td>
        </tr>
}
    </tbody>
</table>

Core_Costumer/Core_Costumer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Core_Costumer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Costumer" asp-action="Index">Core_Costumer</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Costumer" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Core_Costumer - <a asp-area="" asp-controller="Costumer" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>